package predict.stock.base;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import javax.annotation.Nonnull;

public abstract class SPMsg {
    @Nonnull
    public String get_class() {
        return this.getClass().getName();
    }
}
